apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app: test
    env: prod
spec:
  replicas: {{.Values.replicasNumber}}
  selector:
    matchLabels:
      project: new #service will look for these PODs labels
  template:
    metadata:
      labels:
        project: new
    spec:
      containers:
      - name: new-app
        image: {{.Values.container.image}}
        ports:
        - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  labels:
    env: prod
    owner: IlonaMohilnikova
spec:
  selector:
    project: new #selecting PODs with those labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 80 #LoadBalancer
      targetPort: 80 #POD
  type: Cluster IP
